language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - mysql -e 'create database homestead;'
  - mkdir bootstrap/cache
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan migrate
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm run prod

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="6.10.0"
